Sights/Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sights.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
    }
}

Sights/Controllers/Admin/SeancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sights.Models;

namespace Sights.Controllers
{
    public class SeancesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Seances
        public ActionResult Index()
        {
            var seances = db.Seances.Include(s => s.Location).Include(s => s.Showing);
            return View(seances.ToList());
        }

        // GET: Seances/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seance seance = db.Seances.Find(id);
            if (seance == null)
            {
                return HttpNotFound();
            }
            return View(seance);
        }

        // GET: Seances/Create
        public ActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.ShowingId = new SelectList(db.Showings, "Id", "Name");
            return View();
        }

        // POST: Seances/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ShowingId,LocationId,Time,Type")] Seance seance)
        {
            if (ModelState.IsValid)
            {
                db.Seances.Add(seance);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", seance.LocationId);
            ViewBag.ShowingId = new SelectList(db.Showings, "Id", "Name", seance.ShowingId);
            return View(seance);
        }

        // GET: Seances/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seance seance = db.Seances.Find(id);
            if (seance == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", seance.LocationId);
            ViewBag.ShowingId = new SelectList(db.Showings, "Id", "Name", seance.ShowingId);
            return View(seance);
        }

        // POST: Seances/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ShowingId,LocationId,Time,Type")] Seance seance)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seance).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name", seance.LocationId);
            ViewBag.ShowingId = new SelectList(db.Showings, "Id", "Name", seance.ShowingId);
            return View(seance);
        }

        // GET: Seances/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seance seance = db.Seances.Find(id);
            if (seance == null)
            {
                return HttpNotFound();
            }
            return View(seance);
        }

        // POST: Seances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seance seance = db.Seances.Find(id);
            db.Seances.Remove(seance);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sights/Controllers/Admin/ShowingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sights.Models;

namespace Sights.Controllers
{
    public class ShowingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Showings
        public ActionResult Index()
        {
            return View(db.Showings.ToList());
        }

        // GET: Showings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            return View(showing);
        }

        // GET: Showings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Showings/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Author,Name,Description,Genre,Duration,PosterUrl,Date,Type")] Showing showing)
        {
            if (ModelState.IsValid)
            {
                db.Showings.Add(showing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(showing);
        }

        // GET: Showings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            return View(showing);
        }

        // POST: Showings/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Author,Name,Description,Genre,Duration,PosterUrl,Date,Type")] Showing showing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(showing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(showing);
        }

        // GET: Showings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            return View(showing);
        }

        // POST: Showings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Showing showing = db.Showings.Find(id);
            db.Showings.Remove(showing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sights/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Admin/_Layout_Admin.cshtml";
}


<h2>Панель администратора</h2>

<p>Выберите в верхнем меню то, что вы хотите отредактировать.</p>

Sights/Views/Admin/_Layout_Admin.cshtml
<!DOCTYPE html>
<html ng-app="app" >
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Scripts.Render("~/ng")
    @Styles.Render("~/Content/bs")
    @Scripts.Render("~/bundles/modernizr")

    <script>
        angular.module('app', ['ngCookies'])
            .controller('loginCtrl', ['$scope', '$http', '$cookies', '$cookieStore', function ($scope, $http, $cookies, $cookieStore) {
                $scope.logged = false;

                var value = $cookies.get('user');
                if (value != null)
                    $scope.logged = true;

                $scope.logout = function () {
                    $cookies.remove('user');
                    $scope.logged = false;
                }

                $scope.loggin = function () {
                    $scope.showMessage = false;
                    var params = "grant_type=password&username=" + $scope.username + "&password=" + $scope.password;
                    $http({
                        url: '/Token',
                        method: "POST",
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        data: params
                    })
                    .success(function (data, status, headers, config) {

                        $cookieStore.put('user', $scope.username);
                        $scope.logged = true;
                    })
                    .error(function (data, status, headers, config) {
                        $scope.message = $routeParams.message;

                        $scope.errorMessage = data.error_description.replace(/["']{1}/gi, "");
                    });
                }
            }]);
    </script>
</head>
<body ng-controller="loginCtrl">
    <div class="container navbar navbar-default" ng-show="logged">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sights", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("События", "Index", "Showings", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Места", "Index", "Locations", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Сеансы", "Index", "Seances", new { area = "" }, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a ng-show="logged">{{username}}</a></li>
                    <li><a href="javascript:void(0);" ng-click="logout();" ng-show="logged">Выйти</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container" ng-hide="logged" style="margin-top: 200px;">
        <form class="col-lg-offset-4 col-lg-4">
            <div class="form-group">
                <label>Логин</label><br />
                <input class="form-control" type="text" ng-model="username" />
            </div>
            <div class="form-group">
                <label>Пароль</label><br />
                <input class="form-control" type="password" ng-model="password" />
            </div>
            <button class="btn btn-primary" ng-click="loggin()">Войти</button>
        </form>
    </div>
    <div class="container" ng-show="logged">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>